#!/bin/sh
ulimit -c 0
total=0
pathsize=`/usr/bin/du -s --block-size=1 /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details --exclude=group | awk '{print $1}'`
total=$(($total+$pathsize))
group=0
group=`/usr/bin/du -s --block-size=1 /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details/group | awk '{print $1}'`
echo $group > /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details/group/duse_group.tmp && \
mv /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details/group/duse_group.tmp /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details/group/duse_group
pathsize=`/usr/bin/du -s --block-size=1 /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/top.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details/duse_manager_res.tmp && \
mv /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details/duse_manager_res.tmp /mnt/vol_NFS_rh003/estudiantes/DANIELA_VARGAS/Version_final/0516/versiones_finales/semana14/Registro_Hamming/Hamming_16/FLOW/fc_flow/flow/work/signoff_drc_run/run_details/duse_manager_res
